//
// Created by Vladimir on 30.04.2022.
//

#ifndef MAIN_PROJECT_TEST_DATA_SOURCE_H
#define MAIN_PROJECT_TEST_DATA_SOURCE_H


#include "string"

static std::string READING_SOURCE_1 = ""
                                      "{\n"
                                      "    \"Version\": 1.0,\n"
                                      "    \"Influences\": {\n"
                                      "        \"Lag\": {\n"
                                      "            \"Type\": 0,\n"
                                      "            \"X\": 0,\n"
                                      "            \"Y\": 0,\n"
                                      "            \"Z\": 0\n"
                                      "        },\n"
                                      "        \"1\": {\n"
                                      "            \"Influence number\": 1,\n"
                                      "            \"Amplitude\": 100,\n"
                                      "            \"Time function\": {\n"
                                      "                \"Count\": 17,\n"
                                      "                \"Time\": \"0.0 1.0019e-06 1.003e-06 1.004e-06 1.005e-06 1.006e-06 1.007e-06 1.008e-06 1.009e-06 1.01e-06 1.013e-06 1.015e-06 1.02e-06 1.03e-06 1.05e-06 1.079e-06 2e-06\",\n"
                                      "                \"Value\": \"0.0 0.0 9.14641e-06 6.75833e-05 0.000499285 0.00368496 0.0268947 0.179408 0.706193 1.0 0.603564 0.404686 0.148829 0.0201518 0.000369046 1.11759e-06 0.0\"\n"
                                      "            },\n"
                                      "            \"Sources\": {\n"
                                      "                \"Currents\": {},\n"
                                      "                \"Volume\": {\n"
                                      "                    \"Volume_1_0\": {\n"
                                      "                        \"Type\": \"Volume\",\n"
                                      "                        \"Layer index\": 0,\n"
                                      "                        \"Particle index\": 1,\n"
                                      "                        \"Spectre\": \"SP1\",\n"
                                      "                        \"Spectre number\": \"1\"\n"
                                      "                    }\n"
                                      "                },\n"
                                      "                \"Sigmas\": {}\n"
                                      "            }\n"
                                      "        }\n"
                                      "    }\n"
                                      "}"
                                      "";

static std::string SPECTERS = ""
                              " spectrum>\n"
                              "2\n"
                              "SP1\n"
                              "SP2\n"
                              "<Volume78 distributions>\n"
                              "0\n"
                              "Marple Ionization\n"
                              "0"
                              "";


static std::string JSON78 = ""
                            "{\n"
                            "    \"Version\": 1.0,\n"
                            "    \"Influences\": {\n"
                            "        \"Lag\": {\n"
                            "            \"Type\": 0,\n"
                            "            \"X\": 0,\n"
                            "            \"Y\": 0,\n"
                            "            \"Z\": 0\n"
                            "        },\n"
                            "        \"Xray\": {\n"
                            "            \"Influence number\": 1,\n"
                            "            \"Amplitude\": 4.1265e+37,\n"
                            "            \"Time function\": {\n"
                            "                \"Count\": 17,\n"
                            "                \"Time\": \"0.0 1.0019e-06 1.003e-06 1.004e-06 1.005e-06 1.006e-06 1.007e-06 1.008e-06 1.009e-06 1.01e-06 1.013e-06 1.015e-06 1.02e-06 1.03e-06 1.05e-06 1.079e-06 2e-06\",\n"
                            "                \"Value\": \"0.0 0.0 9.14641e-06 6.75833e-05 0.000499285 0.00368496 0.0268947 0.179408 0.706193 1.0 0.603564 0.404686 0.148829 0.0201518 0.000369046 1.11759e-06 0.0\"\n"
                            "            },\n"
                            "            \"Sources\": {\n"
                            "                \"Currents\": {\n"
                            "                    \"Current_x_layer_19\": {\n"
                            "                        \"Type\": \"Current_x\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Distribution\": \"jx_19_1\"\n"
                            "                    },\n"
                            "                    \"Current_y_layer_19\": {\n"
                            "                        \"Type\": \"Current_y\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Distribution\": \"jy_19_1\"\n"
                            "                    },\n"
                            "                    \"Current_z_layer_19\": {\n"
                            "                        \"Type\": \"Current_z\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Distribution\": \"jz_19_1\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Sigmas\": {},\n"
                            "                \"Volume78\": {\n"
                            "                    \"Volume78_1_19\": {\n"
                            "                        \"Type\": \"Volume78\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Spectre\": \"micr_1\",\n"
                            "                        \"Spectre number\": \"1\",\n"
                            "                        \"Distribution\": \"en_19_1\"\n"
                            "                    },\n"
                            "                    \"Volume78_2_19\": {\n"
                            "                        \"Type\": \"Volume78\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Spectre\": \"micr_2\",\n"
                            "                        \"Spectre number\": \"2\",\n"
                            "                        \"Distribution\": \"en_19_1\"\n"
                            "                    }\n"
                            "                }\n"
                            "            }\n"
                            "        },\n"
                            "        \"Gamma\": {\n"
                            "            \"Influence number\": 2,\n"
                            "            \"Amplitude\": 1.705e+33,\n"
                            "            \"Time function\": {\n"
                            "                \"Count\": 38,\n"
                            "                \"Time\": \"0.0 1e-09 2e-09 3e-09 4e-09 5e-09 6e-09 7e-09 8e-09 9e-09 1e-08 1.3e-08 1.5e-08 2e-08 3e-08 5e-08 7.5e-08 1e-07 1.1e-07 1e-06 1.001e-06 1.002e-06 1.003e-06 1.004e-06 1.005e-06 1.006e-06 1.007e-06 1.008e-06 1.009e-06 1.01e-06 1.013e-06 1.015e-06 1.02e-06 1.03e-06 1.05e-06 1.075e-06 1.1e-06 2e-06\",\n"
                            "                \"Value\": \"0.0 4.52095e-05 0.000122832 0.000332857 0.000896491 0.00237341 0.005980274 0.013335533 0.023539765 0.031162688 0.033333333 0.027063396 0.022230778 0.013489532 0.00496095 0.000671727 5.51094e-05 4.52462e-06 0.0 0.0 0.001499285 0.003684963 0.0099857 0.026894731 0.071202288 0.179408206 0.400065999 0.706192938 0.934880651 1.0 0.811901881 0.666923331 0.404685953 0.148828512 0.020151798 0.001653283 0.000135739 0.0\"\n"
                            "            },\n"
                            "            \"Sources\": {\n"
                            "                \"Currents\": {\n"
                            "                    \"Current_x_layer_19\": {\n"
                            "                        \"Type\": \"Current_x\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Distribution\": \"jx_19_2\"\n"
                            "                    },\n"
                            "                    \"Current_y_layer_19\": {\n"
                            "                        \"Type\": \"Current_y\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Distribution\": \"jy_19_2\"\n"
                            "                    },\n"
                            "                    \"Current_z_layer_19\": {\n"
                            "                        \"Type\": \"Current_z\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Distribution\": \"jz_19_2\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Sigmas\": {},\n"
                            "                \"Volume78\": {\n"
                            "                    \"Volume78_3_19\": {\n"
                            "                        \"Type\": \"Volume78\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Particle index\": 3,\n"
                            "                        \"Spectre\": \"micr_1\",\n"
                            "                        \"Spectre number\": \"1\",\n"
                            "                        \"Distribution\": \"en_19_2\"\n"
                            "                    },\n"
                            "                    \"Volume78_4_19\": {\n"
                            "                        \"Type\": \"Volume78\",\n"
                            "                        \"Layer index\": 19,\n"
                            "                        \"Particle index\": 4,\n"
                            "                        \"Spectre\": \"micr_2\",\n"
                            "                        \"Spectre number\": \"2\",\n"
                            "                        \"Distribution\": \"en_19_2\"\n"
                            "                    }\n"
                            "                }\n"
                            "            }\n"
                            "        }\n"
                            "    }\n"
                            "}"
                            "";

static std::string SPECTRES78 = ""
                                "<Particles spectrum>\n"
                                "2\n"
                                "micr_1\n"
                                "micr_2\n"
                                "<Volume78 distributions>\n"
                                "2\n"
                                "en_19_1\n"
                                "en_19_2\n"
                                "Marple Ionization\n"
                                "0"
                                "";

static std::string BIG_RS = ""
                            "{\n"
                            "    \"Version\": 1.0,\n"
                            "    \"Influences\": {\n"
                            "        \"Lag\": {\n"
                            "            \"Type\": 0,\n"
                            "            \"X\": -0.8,\n"
                            "            \"Y\": 0.0,\n"
                            "            \"Z\": -0.6\n"
                            "        },\n"
                            "        \"1\": {\n"
                            "            \"Influence number\": 1,\n"
                            "            \"Amplitude\": 4.1265e+37,\n"
                            "            \"Time function\": {\n"
                            "                \"Count\": 17,\n"
                            "                \"Time\": \"0.0 1.0019e-06 1.003e-06 1.004e-06 1.005e-06 1.006e-06 1.007e-06 1.008e-06 1.009e-06 1.01e-06 1.013e-06 1.015e-06 1.02e-06 1.03e-06 1.05e-06 1.079e-06 2e-06\",\n"
                            "                \"Value\": \"0.0 0.0 9.14641e-06 6.75833e-05 0.000499285 0.00368496 0.0268947 0.179408 0.706193 1.0 0.603564 0.404686 0.148829 0.0201518 0.000369046 1.11759e-06 0.0\"\n"
                            "            },\n"
                            "            \"Sources\": {\n"
                            "                \"Currents\": {\n"
                            "                    \"Current_x_layer_0\": {\n"
                            "                        \"Type\": \"Current_x\",\n"
                            "                        \"Layer index\": 0,\n"
                            "                        \"Distribution\": \"distr\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Surface\": {\n"
                            "                    \"Flu_e_1_1_0\": {\n"
                            "                        \"Type\": \"Flux\",\n"
                            "                        \"Layer index from\": 1,\n"
                            "                        \"Layer index to\": 0,\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Spectre\": \"SP1\",\n"
                            "                        \"Spectre number\": \"1\",\n"
                            "                        \"Direction\": \"-1\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Volume\": {\n"
                            "                    \"Volume_1_0\": {\n"
                            "                        \"Type\": \"Volume\",\n"
                            "                        \"Layer index\": 0,\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Spectre\": \"SP1\",\n"
                            "                        \"Spectre number\": \"1\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"From boundaries\": {\n"
                            "                    \"Boundaries_1_X\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Direction\": 1,\n"
                            "                        \"Spectre\": \"xmax_part1\",\n"
                            "                        \"Spectre number\": \"9\"\n"
                            "                    },\n"
                            "                    \"Boundaries_1_Y\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Direction\": 3,\n"
                            "                        \"Spectre\": \"ymax_part1\",\n"
                            "                        \"Spectre number\": \"8\"\n"
                            "                    },\n"
                            "                    \"Boundaries_1_Z\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Direction\": 5,\n"
                            "                        \"Spectre\": \"zmax_part1\",\n"
                            "                        \"Spectre number\": \"7\"\n"
                            "                    },\n"
                            "                    \"Boundaries_1_-X\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Direction\": 0,\n"
                            "                        \"Spectre\": \"xmin_part1\",\n"
                            "                        \"Spectre number\": \"11\"\n"
                            "                    },\n"
                            "                    \"Boundaries_1_-Y\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Direction\": 2,\n"
                            "                        \"Spectre\": \"ymin_part1\",\n"
                            "                        \"Spectre number\": \"12\"\n"
                            "                    },\n"
                            "                    \"Boundaries_1_-Z\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 1,\n"
                            "                        \"Direction\": 4,\n"
                            "                        \"Spectre\": \"zmin_part1\",\n"
                            "                        \"Spectre number\": \"13\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Sigmas\": {\n"
                            "                    \"Sigma_layer_0\": {\n"
                            "                        \"Type\": \"Sigma\",\n"
                            "                        \"Layer index\": 0,\n"
                            "                        \"Distribution\": \"distr\"\n"
                            "                    }\n"
                            "                }\n"
                            "            }\n"
                            "        },\n"
                            "        \"2\": {\n"
                            "            \"Influence number\": 2,\n"
                            "            \"Amplitude\": 1.9993e+33,\n"
                            "            \"Time function\": {\n"
                            "                \"Count\": 38,\n"
                            "                \"Time\": \"0.0 1e-09 2e-09 3e-09 4e-09 5e-09 6e-09 7e-09 8e-09 9e-09 1e-08 1.3e-08 1.5e-08 2e-08 3e-08 5e-08 7.5e-08 1e-07 1.1e-07 1e-06 1.001e-06 1.002e-06 1.003e-06 1.004e-06 1.005e-06 1.006e-06 1.007e-06 1.008e-06 1.009e-06 1.01e-06 1.013e-06 1.015e-06 1.02e-06 1.03e-06 1.05e-06 1.075e-06 1.1e-06 2e-06\",\n"
                            "                \"Value\": \"0.0 4.52095e-05 0.000122832 0.000332857 0.000896491 0.00237341 0.005980274 0.013335533 0.023539765 0.031162688 0.033333333 0.027063396 0.022230778 0.013489532 0.00496095 0.000671727 5.51094e-05 4.52462e-06 0.0 0.0 0.001499285 0.003684963 0.0099857 0.026894731 0.071202288 0.179408206 0.400065999 0.706192938 0.934880651 1.0 0.811901881 0.666923331 0.404685953 0.148828512 0.020151798 0.001653283 0.000135739 0.0\"\n"
                            "            },\n"
                            "            \"Sources\": {\n"
                            "                \"Currents\": {},\n"
                            "                \"Surface\": {\n"
                            "                    \"Flu_e_2_1_0\": {\n"
                            "                        \"Type\": \"Flux\",\n"
                            "                        \"Layer index from\": 1,\n"
                            "                        \"Layer index to\": 0,\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Spectre\": \"1_0_0_2.spc 1_0_1_2.spc 1_0_2_2.spc 1_0_3_2.spc 1_0_4_2.spc 1_0_5_2.spc\",\n"
                            "                        \"Spectre number\": \"10002 10012 10022 10032 10042 10052\",\n"
                            "                        \"Direction\": \"0 1 2 3 4 5\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Volume\": {\n"
                            "                    \"Volume_2_0\": {\n"
                            "                        \"Type\": \"Volume\",\n"
                            "                        \"Layer index\": 0,\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Spectre\": \"SP2\",\n"
                            "                        \"Spectre number\": \"2\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"From boundaries\": {\n"
                            "                    \"Boundaries_2_X\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Direction\": 1,\n"
                            "                        \"Spectre\": \"xmax_part2\",\n"
                            "                        \"Spectre number\": \"19\"\n"
                            "                    },\n"
                            "                    \"Boundaries_2_Y\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Direction\": 3,\n"
                            "                        \"Spectre\": \"ymax_part2\",\n"
                            "                        \"Spectre number\": \"18\"\n"
                            "                    },\n"
                            "                    \"Boundaries_2_Z\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Direction\": 5,\n"
                            "                        \"Spectre\": \"zmax_part2\",\n"
                            "                        \"Spectre number\": \"17\"\n"
                            "                    },\n"
                            "                    \"Boundaries_2_-X\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Direction\": 0,\n"
                            "                        \"Spectre\": \"xmin_part2\",\n"
                            "                        \"Spectre number\": \"21\"\n"
                            "                    },\n"
                            "                    \"Boundaries_2_-Y\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Direction\": 2,\n"
                            "                        \"Spectre\": \"ymin_part2\",\n"
                            "                        \"Spectre number\": \"22\"\n"
                            "                    },\n"
                            "                    \"Boundaries_2_-Z\": {\n"
                            "                        \"Type\": \"Boundaries\",\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Direction\": 4,\n"
                            "                        \"Spectre\": \"zmin_part2\",\n"
                            "                        \"Spectre number\": \"23\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Volume78\": {\n"
                            "                    \"Volume78_2_0\": {\n"
                            "                        \"Type\": \"Volume78\",\n"
                            "                        \"Layer index\": 0,\n"
                            "                        \"Particle index\": 2,\n"
                            "                        \"Spectre\": \"SP1\",\n"
                            "                        \"Spectre number\": \"1\",\n"
                            "                        \"Distribution\": \"distr\"\n"
                            "                    }\n"
                            "                },\n"
                            "                \"Sigmas\": {}\n"
                            "            }\n"
                            "        }\n"
                            "    }\n"
                            "}"
                            "";

static std::string BIG_RS_SPECTRES = ""
                                     "<Particles spectrum>\n"
                                     "21\n"
                                     "SP1\n"
                                     "SP1\n"
                                     "xmax_part1\n"
                                     "ymax_part1\n"
                                     "zmax_part1\n"
                                     "xmin_part1\n"
                                     "ymin_part1\n"
                                     "zmin_part1\n"
                                     "1_0_0_2.spc\n"
                                     "1_0_1_2.spc\n"
                                     "1_0_2_2.spc\n"
                                     "1_0_3_2.spc\n"
                                     "1_0_4_2.spc\n"
                                     "1_0_5_2.spc\n"
                                     "SP2\n"
                                     "xmax_part2\n"
                                     "ymax_part2\n"
                                     "zmax_part2\n"
                                     "xmin_part2\n"
                                     "ymin_part2\n"
                                     "zmin_part2\n"
                                     "<Volume78 distributions>\n"
                                     "1\n"
                                     "distr\n"
                                     "Marple Ionization\n"
                                     "0"
                                     "";
#endif //MAIN_PROJECT_TEST_DATA_SOURCE_H
